site_name: Advanced Configurations
site_description: Advanced configurations for containers
site_url: https://virtualize.link/
edit_uri: ""
repo_url: https://github.com/quietsy/advanced-configurations
theme:
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - content.code.copy
    - navigation.instant
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
  name: material
  custom_dir: overrides
  favicon: images/logo.png
  logo: images/logo.png
  font:
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.blocks.html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - admonition
  - pymdownx.details
extra:
  social:
    - icon: fontawesome/solid/rss 
      link: /feed_rss_created.xml
  homepage: https://virtualize.link
plugins:
  - tags
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
      enable_creation_date: true
      enabled: true
  - search
  - rss:
      match_path: .*/.*.md 
      date_from_meta:
        as_creation: date
      image: https://virtualize.link/images/logo.png
      pretty_print: true
      categories:
        - categories
        - tags 
  - redirects:
      redirect_maps:
        'awesome-lsio.md': 'https://docs.linuxserver.io/images-by-category/'
        'secure.md': 'https://www.linuxserver.io/blog/securing-swag'
        'asus-vlans.md': 'Network/asus-vlans.md'
        'atuin.md': 'Other/atuin.md'
        'brave.md': 'Other/brave.md'
        'consolidate.md': 'Containers/consolidating-proxies.md'
        'container-dns.md': 'Containers/container-dns.md'
        'firehol.md': 'Network/firehol.md'
        'geoblock.md': 'Network/geoblock.md'
        'hardcoded-dns.md': 'Network/hardcoded-dns.md'
        'hub.md': 'Containers/wireguard-hub.md'
        'nextcloud.md': 'Containers/optimizing-nextcloud.md'
        'opnarp.md': 'Network/opn-arp.md'
        'phone.md': 'Other/phone.md'
        'piped.md': 'Containers/piped.md'
        'searx.md': 'Containers/searx-ng.md'
        'setup.md': 'Other/setup.md'
        'simplelogin.md': 'Containers/simplelogin.md'
        'smartd.md': 'Other/smartd.md'
        'socks.md': 'Containers/socks-proxy.md'
        'split-dns.md': 'Network/split-dns.md'
        'split.md': 'Network/split-tunnel.md'
        'tmux.md': 'Other/tmux.md'
        'vpn.md': 'Containers/vpn-route.md'
        'vps.md': 'Containers/vps-proxy.md'
        'yaml-anchors.md': 'Containers/yaml-anchors.md'
        'zfs.md': 'Other/zfs.md'
